# Build JAVA applications using Apache Maven
#
# Author: Martijn Raats

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - /root/.m2/repository/
  
verify:
  image: maven:latest
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master
    - release

deploy:
  image: maven:latest
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - master

release:
  image: maven:latest
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  artifacts:
    paths:
    - "target/*.jar"
    - "target/*.war"
    - "target/*.ear"
    - "*/target/*.jar"
    - "*/target/*.war"
    - "*/target/*.ear"
  only:
    - release